/**
 * INTERNAL AUDIT — Management Status Report PDF.
 *
 * Rendered from the canonical snapshot/live payload only. No figure is
 * recomputed here: the PDF is a presentation of `ia_management_status_live`.
 */
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import {
  DEFAULT_AUDIT_BRANDING,
  renderCoverPage,
  renderFooter,
  renderSectionHeading,
  type ExportBranding,
} from '@/lib/audit/auditExportPrimitives';
import type { ManagementStatusPayload } from '@/services/audit/managementStatusReportService';

export interface ManagementStatusPdfMeta {
  reportNumber?: string | null;
  reportingPeriod?: string | null;
  generatedBy?: string | null;
  comparison?: Record<string, any> | null;
}

function fmtDate(v: string | null | undefined): string {
  if (!v) return '—';
  const d = new Date(v);
  return Number.isNaN(d.getTime()) ? String(v) : d.toISOString().slice(0, 10);
}

export function buildManagementStatusPdf(
  data: ManagementStatusPayload,
  meta: ManagementStatusPdfMeta = {},
): jsPDF {
  const doc = new jsPDF({ orientation: 'landscape' });
  const branding: ExportBranding = DEFAULT_AUDIT_BRANDING;
  const pw = doc.internal.pageSize.getWidth();
  const margin = 14;
  const k = data.kpis || {};

  // ── Cover / document control ──
  renderCoverPage(doc, branding, {
    title: 'Audit Plan Status & Management Report',
    metadata: [
      { label: 'Report Number', value: meta.reportNumber || 'Live status (unsealed)' },
      { label: 'Annual Plan', value: data.plan?.title ?? '—' },
      { label: 'Fiscal Year', value: data.plan?.fiscal_year ?? '—' },
      { label: 'Plan Version', value: String(data.plan?.version ?? 1) },
      { label: 'Report Mode', value: data.report_mode || 'Detailed Management Report' },
      {
        label: 'Reporting Period',
        value: data.period
          ? `${data.period.label} — ${fmtDate(data.period.start)} to ${fmtDate(data.period.end)}`
          : meta.reportingPeriod || '—',
      },
      { label: 'Cumulative Status As At', value: fmtDate(data.as_at) },
      { label: 'Audience', value: data.audience ?? '—' },
      { label: 'Generated By', value: meta.generatedBy || '—' },
    ],
    showConfidentiality: true,
  });


  // ── Executive summary + plan health ──
  doc.addPage();
  let y = renderSectionHeading(doc, branding, 'Executive Summary & Plan Health', 18) ?? 30;
  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(40, 40, 40);
  const health = data.health?.rating ?? 'GREEN';
  const summary =
    `Plan health is ${health}. ${k.approved_engagements ?? 0} engagement(s) are in the approved portfolio: ` +
    `${k.closed ?? 0} closed, ${k.closed_actions_pending ?? 0} closed with actions pending, ` +
    `${k.in_progress ?? 0} in progress, ${k.planned_not_started ?? 0} not started, ` +
    `${k.cancelled ?? 0} cancelled and ${k.carried_forward ?? 0} carried forward. ` +
    `Plan completion is ${k.plan_completion_pct ?? 0}% with ${k.schedule_adherence_pct ?? 0}% schedule adherence. ` +
    `${data.findings?.open_critical_high ?? 0} Critical/High finding(s) remain open and ` +
    `${data.actions?.overdue ?? 0} corrective action(s) are overdue.`;
  doc.text(doc.splitTextToSize(summary, pw - margin * 2), margin, y + 4);
  y += 26;
  doc.setFontSize(8);
  doc.setTextColor(110, 110, 110);
  doc.text(`Health basis: ${data.health?.basis ?? ''}`, margin, y);

  // ── KPI dashboard ──
  autoTable(doc, {
    startY: y + 6,
    head: [['Executive KPI', 'Value', 'Executive KPI', 'Value']],
    body: [
      ['Approved engagements', String(k.approved_engagements ?? 0), 'Plan completion %', `${k.plan_completion_pct ?? 0}%`],
      ['Closed', String(k.closed ?? 0), 'Schedule adherence %', `${k.schedule_adherence_pct ?? 0}%`],
      ['Closed – Actions Pending', String(k.closed_actions_pending ?? 0), 'Critical / High findings open', String(data.findings?.open_critical_high ?? 0)],
      ['In progress', String(k.in_progress ?? 0), 'Overdue management responses', String(data.findings?.overdue_responses ?? 0)],
      ['Planned / not started', String(k.planned_not_started ?? 0), 'Open corrective actions', String(data.actions?.open ?? 0)],
      ['Delayed / at risk', String(k.delayed_at_risk ?? 0), 'Overdue corrective actions', String(data.actions?.overdue ?? 0)],
      ['Cancelled', String(k.cancelled ?? 0), 'Follow-ups due', String(data.prior_history?.follow_ups_due ?? 0)],
      ['Carried forward', String(k.carried_forward ?? 0), 'Follow-ups overdue', String(data.prior_history?.follow_ups_overdue ?? 0)],
    ],
    theme: 'grid',
    styles: { fontSize: 8, cellPadding: 2.5 },
    headStyles: { fillColor: branding.primaryColor, textColor: branding.white, fontSize: 8 },
    alternateRowStyles: { fillColor: branding.lightGray },
    margin: { left: margin, right: margin },
  });

  // ── Engagement status ──
  doc.addPage();
  renderSectionHeading(doc, branding, 'Engagement Status', 18);
  autoTable(doc, {
    startY: 30,
    head: [[
      'Reference', 'Audit', 'Department', 'Risk', 'Qtr', 'Planned', 'Actual',
      'Stage', 'Progress', 'Schedule', 'Var (d)', 'Lead', 'Find.', 'Open act.', 'Opinion', 'Next milestone',
    ]],
    body: (data.engagements ?? []).map((e) => [
      e.engagement_code ?? '—',
      e.engagement_name ?? '—',
      e.department_name ?? '—',
      e.risk_rating ?? '—',
      e.quarter ?? '—',
      `${fmtDate(e.planned_start)} → ${fmtDate(e.planned_end)}`,
      `${fmtDate(e.actual_start)} → ${fmtDate(e.actual_end)}`,
      e.lifecycle_status ?? '—',
      `${e.progress_pct ?? 0}%`,
      e.schedule_health ?? '—',
      String(e.variance_days ?? 0),
      e.lead_auditor ?? '—',
      String(e.findings_total ?? 0),
      String(e.open_actions ?? 0),
      e.audit_opinion ?? '—',
      e.next_milestone ?? '—',
    ]),
    theme: 'grid',
    styles: { fontSize: 6.5, cellPadding: 1.8, overflow: 'linebreak' },
    headStyles: { fillColor: branding.primaryColor, textColor: branding.white, fontSize: 6.5 },
    alternateRowStyles: { fillColor: branding.lightGray },
    margin: { left: margin, right: margin },
  });

  // ── Findings, actions, prior issues, capacity ──
  doc.addPage();
  renderSectionHeading(doc, branding, 'Findings, Corrective Actions, Prior Issues & Capacity', 18);
  const sev = data.findings?.by_severity ?? {};
  autoTable(doc, {
    startY: 30,
    head: [['Findings & risk', 'Value', 'Corrective actions', 'Value', 'Prior issues / follow-up', 'Value']],
    body: [
      ['Critical', String(sev.CRITICAL ?? 0), 'Open', String(data.actions?.open ?? 0), 'Prior open actions', String(data.prior_history?.prior_open_actions ?? 0)],
      ['High', String(sev.HIGH ?? 0), 'In progress', String(data.actions?.in_progress ?? 0), 'Prior Critical/High findings', String(data.prior_history?.prior_critical_high_findings ?? 0)],
      ['Medium', String(sev.MEDIUM ?? 0), 'Awaiting verification', String(data.actions?.awaiting_verification ?? 0), 'Follow-ups due', String(data.prior_history?.follow_ups_due ?? 0)],
      ['Low', String(sev.LOW ?? 0), 'Verified / closed', String(data.actions?.verified ?? 0), 'Follow-ups overdue', String(data.prior_history?.follow_ups_overdue ?? 0)],
      ['Open Critical / High', String(data.findings?.open_critical_high ?? 0), 'Overdue', String(data.actions?.overdue ?? 0), 'Partially implemented', String(data.prior_history?.partially_implemented ?? 0)],
      ['Disputed findings', String(data.findings?.disputed ?? 0), 'Due within 30 days', String(data.actions?.due_soon ?? 0), 'Repeat / prior-year findings', String(data.findings?.repeat_prior_year ?? 0)],
      ['Overdue management responses', String(data.findings?.overdue_responses ?? 0), 'Overdue > 90 days', String(data.actions?.ageing?.gt_90 ?? 0), 'Allocated vs available hours',
        `${data.capacity?.allocated_hours ?? 0} / ${data.capacity?.available_hours ?? 0}`],
    ],
    theme: 'grid',
    styles: { fontSize: 8, cellPadding: 2.2 },
    headStyles: { fillColor: branding.primaryColor, textColor: branding.white, fontSize: 8 },
    alternateRowStyles: { fillColor: branding.lightGray },
    margin: { left: margin, right: margin },
  });

  // ── Changes since previous report ──
  if (meta.comparison) {
    const c = meta.comparison;
    autoTable(doc, {
      startY: (doc as any).lastAutoTable.finalY + 8,
      head: [[`Changes since ${c.previous_report_number ?? 'previous report'} (${fmtDate(c.previous_as_at)})`, 'Count']],
      body: [
        ['Engagements started', String(c.engagements_started ?? 0)],
        ['Engagements closed', String(c.engagements_closed ?? 0)],
        ['New delays', String(c.new_delays ?? 0)],
        ['New Critical / High findings', String(c.new_critical_high_findings ?? 0)],
        ['Actions closed', String(c.actions_closed ?? 0)],
        ['Actions newly overdue', String(c.actions_newly_overdue ?? 0)],
        ['Audits rescheduled', String(c.rescheduled ?? 0)],
        ['Audits cancelled', String(c.newly_cancelled ?? 0)],
        ['Audits carried forward', String(c.newly_carried_forward ?? 0)],
        ['Plan amendments', String(c.plan_amendments ?? 0)],
        ['Plan completion change', `${c.plan_completion_delta ?? 0}%`],
      ],
      theme: 'grid',
      styles: { fontSize: 8, cellPadding: 2.2 },
      headStyles: { fillColor: branding.primaryColor, textColor: branding.white, fontSize: 8 },
      margin: { left: margin, right: margin },
    });
  }

  // ── Management attention / decisions required ──
  doc.addPage();
  renderSectionHeading(doc, branding, 'Management Attention & Decisions Required', 18);
  const attention = data.management_attention ?? [];
  autoTable(doc, {
    startY: 30,
    head: [['Severity', 'Category', 'Matter', 'Source']],
    body: attention.length
      ? attention.map((a) => [a.severity, a.category, a.title, a.link])
      : [['—', 'None', 'No exceptional matters requiring management decision at this date.', '—']],
    theme: 'grid',
    styles: { fontSize: 8, cellPadding: 2.2, overflow: 'linebreak' },
    headStyles: { fillColor: branding.primaryColor, textColor: branding.white, fontSize: 8 },
    columnStyles: { 0: { cellWidth: 22 }, 1: { cellWidth: 62 }, 3: { cellWidth: 78 } },
    margin: { left: margin, right: margin },
  });

  // ── Plan change governance + outlook ──
  const amendments: any[] = data.plan_changes?.amendments ?? [];
  autoTable(doc, {
    startY: (doc as any).lastAutoTable.finalY + 8,
    head: [['Plan change governance (original commitments retained)', 'Detail', 'Reason', 'Status', 'Date']],
    body: amendments.length
      ? amendments.map((a) => [
          a.amendment_type ?? '—',
          `${a.field ?? ''} ${a.old_value ?? ''} → ${a.new_value ?? ''}`.trim(),
          a.reason ?? '—',
          a.status ?? '—',
          fmtDate(a.date),
        ])
      : [['No amendments', '—', '—', '—', '—']],
    theme: 'grid',
    styles: { fontSize: 8, cellPadding: 2.2, overflow: 'linebreak' },
    headStyles: { fillColor: branding.primaryColor, textColor: branding.white, fontSize: 8 },
    margin: { left: margin, right: margin },
  });

  renderFooter(doc, branding);
  return doc;
}

export function downloadManagementStatusPdf(
  data: ManagementStatusPayload,
  meta: ManagementStatusPdfMeta = {},
) {
  const doc = buildManagementStatusPdf(data, meta);
  doc.save(`${meta.reportNumber || 'Audit-Plan-Management-Status'}.pdf`);
}

export function managementStatusPdfBlob(
  data: ManagementStatusPayload,
  meta: ManagementStatusPdfMeta = {},
): Blob {
  return buildManagementStatusPdf(data, meta).output('blob');
}
